name: data200s
channels:
  - conda-forge
  - default
dependencies:
  - python=3.11
  - pathlib
  - tqdm
  - numpy
  - pandas
  - seaborn
  - jupyterlab
  - ipykernel
  - scikit-image
  - scikit-learn
  - black
  - flake8
  - gdown
  - unzip
  - zip
  - opencv
  - tensorflow
  - pillow
